Update workloads base image
basisai/docker-workload pull request #157
Opened 2021-12-21 04:56 UTC by tunguyen9889

2021-12-21 08:17 UTC, gyng reviewed
:100:

2021-12-21 08:17 UTC, gyng commented on .github/workflows/ci.yaml
> +          push: true
Is this for testing?

2021-12-21 08:24 UTC, tunguyen9889 commented on .github/workflows/ci.yaml
> +          push: true
yes, I temporary changed it to force push image.

2021-12-22 06:00 UTC, sweatybridge approved these changes

2021-12-22 06:00 UTC, sweatybridge commented on Dockerfile
> +    build-essential \
Run succeeded: https://amoy.ai/project/view/qiao/training/pipeline/view/churn-aws/run/10/step/preprocess/logs

```suggestion
    build-essential \
```

`gcc` is included in `build-essential`.

2021-12-22 06:02 UTC, sweatybridge commented on pom.xml
> +			<version>1.12.129</version>
Since we've upgraded to hadoop-aws 3.3.1, do we still need this separate dependency?

2021-12-22 06:03 UTC, sweatybridge commented on pom.xml
> +			<version>1.12.129</version>
seems like we need it https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws/3.3.1

2021-12-22 06:05 UTC, sweatybridge requested changes
let me test on gcp before approving

2021-12-22 06:23 UTC, sweatybridge commented on pom.xml
>  			<!-- Can be removed after upgrading to hadoop 3.3.0 -->
```suggestion
			<!-- Can be removed after upgrading to hadoop 3.3.0 -->
```
we can remove these dependencies after upgrading to spark 3.2

2021-12-22 07:13 UTC, sweatybridge approved these changes

2021-12-22 07:16 UTC, merged